### PR TITLE
Export ProvidedAccessTokenStrategy

### LINKED ISSUE #79: Refresh not working with auth code flow?
Hey there,

I want to use the library in a nodejs service where access and refresh token are already prepared. Thus I use the `withAccessToken()` method. When calling the `authenticate()` function with an expired token it obviously tries to refresh it. Sadly the client receives `invalid_request` from the api. I suspect the reason is the missing Authorization header. The API specifies the refresh request to use basic authentication with client_id and secret_key and supply `grant_type=refresh_token&refresh_token=...`. Additionally a client_id body param is required for PKCE method. From the code https://github.com/spotify/spotify-web-api-ts-sdk/blob/main/src/auth/AccessTokenHelpers.ts#L28 we see there is not authorization header passed. 

Am I doing or use the library in a wrong way? Or is that a missing feature?

Example code
```
  const spotify = SpotifyApi.withAccessToken(config.spotify.clientId, {
    token_type: 'Bearer',
    access_token: config.spotify.accessToken,
    refresh_token: config.spotify.refreshToken,
    expires_in: config.spotify.expiresAt.getTime() - Date.now(),
    expires: config.spotify.expiresAt.getTime(),
  });

  const params = request.nextUrl.searchParams;
  const search = params.get('search');
  const type = params.get('type');

  // Will attempt refresh of token and fails with invalid_request
  await spotify.authenticate()

  const result = await spotify.search(search, [type as ItemTypes])
```

Thanks in advance and best regards

### PR DESCRIPTION
**Pull request by zhammer**
Resolves #79

### CODE REVIEW

**Comment by fostertheweb** [comment]
@zhammer I added your change to [my fork](https://github.com/fostertheweb/spotify-web-sdk) and published it to npm.

**Comment by zhammer** [comment]
woo thanks

**Comment by zhammer** [comment]
would love to see this in a release !

**Comment by zhammer** [comment]
@jordan-loeser bump on this if it could be added to a release!

**Comment by eimerreis** [comment]
@jordan-loeser  bumping as well 🙂 would really appreciate to see this in a release

**Pull request merged**
